on: [pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      env:
        SALESFORCE_SDK_CLIENT_ID: ${{ secrets.SALESFORCE_SDK_CLIENT_ID }}
        SALESFORCE_SDK_CLIENT_SECRET: ${{ secrets.SALESFORCE_SDK_CLIENT_SECRET }}
        SALESFORCE_SDK_USERNAME: ${{ secrets.SALESFORCE_SDK_USERNAME }}
        SALESFORCE_SDK_PASSWORD: ${{ secrets.SALESFORCE_SDK_PASSWORD }}
        SALESFORCE_SDK_SECURITY_TOKEN: ${{ secrets.SALESFORCE_SDK_SECURITY_TOKEN }}
      run: go test ./... -v -tags=


